#include <PGS_TYPES.h>

#ifndef _PGS_MET_NEW_H
#define _PGS_MET_NEW_H
#define MAX_NUM_FILES 256
#define FILE_ID_BASE 10001
#define PGSd_MET_PATH_LENGTH_MAX 768
#define PGSd_MET_TEMP_ENVIRONMENT "PGS_TEMPORARY_IO"
#define PGSd_MET_INTER_OUTPUT_ENVIRONMENT "PGS_INTERMEDIATE_OUTPUT"
#define PGSd_MET_INFO_FILE_ENVIRONMENT "PGS_PC_INFO_FILE"
typedef PGSt_integer PGSt_MET_Long_Int;  /* for backwards compatibility */
typedef PGSt_Logical  PGSt_MET_Logical;
#define PGSd_MET_FILE_NAME_MAX 256
#define PGSd_MET_FILE_PATH_MAX 1025
#define PGSd_MET_UREF_LENGTH_MAX 255
#define PGSd_MET_INTERMEDIATE_OUTPUT 5500
#define PGSd_MET_INTERMEDIATE_INPUT 5400
#define PGSd_MET_TEMPORARY_FILE 5300
#define PGSd_MET_INPUT_FILE_NAME 5600 
#define PGSd_MET_OUTPUT_FILE_NAME 5700
#define PGSd_MET_SUPPORT_IN_NAME 5800
#define PGSd_MET_SUPPORT_OUT_NAME 5900
#define PGSd_MET_VALUE_LENGTH_MAX 200
#define PGSd_MET_LINE_LENGTH_MAX 2000
#define PGSd_MET_CONFIGURATION 5000
#define PGSd_MET_INPUT_FILE_ATTRIBUTE 5110
#define PGSd_MET_OUTPUT_FILE_ATTRIBUTE 5210
#define PGSd_MET_SUPPORT_IN_ATTR 5610
#define PGSd_MET_SUPPORT_OUT_ATTR 5710
#define PGSd_MET_ATTRIBUTE_STRING 2
#define PGSd_MET_PRODUCTION_RUN_ID 1
#define PGSd_MET_ATTRIBUTE_LOCATION 1

#define PGSd_PC_PATH_LENGTH_MAX 768
#define PGSd_PC_TEMP_ENVIRONMENT "PGS_TEMPORARY_IO"
#define PGSd_PC_INTER_OUTPUT_ENVIRONMENT "PGS_INTERMEDIATE_OUTPUT"
#define PGSd_PC_INFO_FILE_ENVIRONMENT "PGS_PC_INFO_FILE"
#define PGSd_PC_FILE_NAME_MAX 256
#define PGSd_PC_FILE_PATH_MAX 1025
#define PGSd_PC_UREF_LENGTH_MAX 255
#define PGSd_PC_INTERMEDIATE_OUTPUT 5500
#define PGSd_PC_INTERMEDIATE_INPUT 5400
#define PGSd_PC_TEMPORARY_FILE 5300
#define PGSd_PC_INPUT_FILE_NAME 5600 
#define PGSd_PC_OUTPUT_FILE_NAME 5700
#define PGSd_PC_SUPPORT_IN_NAME 5800
#define PGSd_PC_SUPPORT_OUT_NAME 5900
#define PGSd_PC_VALUE_LENGTH_MAX 200
#define PGSd_PC_LINE_LENGTH_MAX 2000
#define PGSd_PC_CONFIGURATION 5000
#define PGSd_PC_INPUT_FILE_ATTRIBUTE 5110
#define PGSd_PC_OUTPUT_FILE_ATTRIBUTE 5210
#define PGSd_PC_SUPPORT_IN_ATTR 5610
#define PGSd_PC_SUPPORT_OUT_ATTR 5710
#define PGSd_PC_ATTRIBUTE_STRING 2
#define PGSd_PC_PRODUCTION_RUN_ID 1
#define PGSd_PC_ATTRIBUTE_LOCATION 1
#define PGSd_PC_CONFIG_COUNT 6
#define PGSd_PC_DIVIDER '?'
#define PGSd_PC_COMMENT '#'
#define PGSd_PC_DELIMITER '|'
#define PGSd_PC_NEWLINE '\n'
#define USER_SETS_HDFID 100 /* if user wants the PGS_MET_Write to output
			       metadata to a file other than hdf and AsciiDump
			       file */
#endif
