        INTEGER PGSMET_E_NONE
        PARAMETER (PGSMET_E_NONE = 10000)
        INTEGER PGSMET_E_NO_INITIALIZATION
        PARAMETER (PGSMET_E_NO_INITIALIZATION = 10001)
        INTEGER PGSMET_E_AGGREGATE_ERR
        PARAMETER (PGSMET_E_AGGREGATE_ERR = 10002)
        INTEGER PGSMET_E_OPEN_ERR
        PARAMETER (PGSMET_E_OPEN_ERR = 10003)
        INTEGER PGSMET_E_ODL_READ_ERR
        PARAMETER (PGSMET_E_ODL_READ_ERR = 10004)
        INTEGER PGSMET_E_LOAD_ERR
        PARAMETER (PGSMET_E_LOAD_ERR = 10005)
        INTEGER PGSMET_E_DD_UNKNOWN_PARM
        PARAMETER (PGSMET_E_DD_UNKNOWN_PARM = 10006)
        INTEGER PGSMET_E_UNKNOWN_PARM_ATTR
        PARAMETER (PGSMET_E_UNKNOWN_PARM_ATTR = 10007)
        INTEGER PGSMET_E_CORRUPT_MCF
        PARAMETER (PGSMET_E_CORRUPT_MCF = 10008)
        INTEGER PGSMET_E_PARM_NOT_SET
        PARAMETER (PGSMET_E_PARM_NOT_SET = 10009)
        INTEGER PGSMET_W_NO_MAND_PARM
        PARAMETER (PGSMET_W_NO_MAND_PARM = 10010)
        INTEGER PGSMET_E_INV_ODL_TYPE
        PARAMETER (PGSMET_E_INV_ODL_TYPE = 10011)
        INTEGER PGSMET_E_OUTOFRANGE
        PARAMETER (PGSMET_E_OUTOFRANGE = 10012)
        INTEGER PGSMET_E_DD_ERR
        PARAMETER (PGSMET_E_DD_ERR = 10013)
        INTEGER PGSMET_E_MCF_DD_CONFLICT
        PARAMETER (PGSMET_E_MCF_DD_CONFLICT = 10014)
        INTEGER PGSMET_E_PCS_OPEN_ERR
        PARAMETER (PGSMET_E_PCS_OPEN_ERR = 10015)
        INTEGER PGSMET_E_LABEL_NOT_FOUND
        PARAMETER (PGSMET_E_LABEL_NOT_FOUND = 10016)
        INTEGER PGSMET_E_CONFIG_VAL_STR_ERR
        PARAMETER (PGSMET_E_CONFIG_VAL_STR_ERR = 10017)
        INTEGER PGSMET_E_CONFIG_CONV_ERR
        PARAMETER (PGSMET_E_CONFIG_CONV_ERR = 10018)
        INTEGER PGSMET_E_INCORRECT_VAL
        PARAMETER (PGSMET_E_INCORRECT_VAL = 10019)
        INTEGER PGSMET_E_NO_INVENT_DATA
        PARAMETER (PGSMET_E_NO_INVENT_DATA = 10020)
        INTEGER PGSMET_E_CONFIG_DATA_ERR
        PARAMETER (PGSMET_E_CONFIG_DATA_ERR = 10021)
        INTEGER PGSMET_E_CONFIRM_ERR
        PARAMETER (PGSMET_E_CONFIRM_ERR = 10022)
        INTEGER PGSMET_E_LOCATION_ERR
        PARAMETER (PGSMET_E_LOCATION_ERR = 10023)
        INTEGER PGSMET_E_NEW_ODL_DATA_ERR
        PARAMETER (PGSMET_E_NEW_ODL_DATA_ERR = 10024)
        INTEGER PGSMET_E_INVALID_DATATYPE
        PARAMETER (PGSMET_E_INVALID_DATATYPE = 10025)
        INTEGER PGSMET_E_CHECK_RANGE_ERR
        PARAMETER (PGSMET_E_CHECK_RANGE_ERR = 10026)
        INTEGER PGSMET_E_PCREAD_ERR
        PARAMETER (PGSMET_E_PCREAD_ERR = 10027)
        INTEGER PGSMET_E_FILETOODL_ERR
        PARAMETER (PGSMET_E_FILETOODL_ERR = 10028)
        INTEGER PGSMET_E_SYS_OPEN_ERR
        PARAMETER (PGSMET_E_SYS_OPEN_ERR = 10029)
        INTEGER PGSMET_E_ODLTOVAL_ERR
        PARAMETER (PGSMET_E_ODLTOVAL_ERR = 10030)
        INTEGER PGSMET_E_SD_START
        PARAMETER (PGSMET_E_SD_START = 10031)
        INTEGER PGSMET_E_SD_FINDATTR
        PARAMETER (PGSMET_E_SD_FINDATTR = 10032)
        INTEGER PGSMET_E_SD_INFO
        PARAMETER (PGSMET_E_SD_INFO = 10033)
        INTEGER PGSMET_E_MALLOC_ERR
        PARAMETER (PGSMET_E_MALLOC_ERR = 10034)
        INTEGER PGSMET_E_SD_READ
        PARAMETER (PGSMET_E_SD_READ = 10035)
        INTEGER PGSMET_W_CLASS_TYPE
        PARAMETER (PGSMET_W_CLASS_TYPE = 10036)
        INTEGER PGSMET_E_SD_SETATTR
        PARAMETER (PGSMET_E_SD_SETATTR = 10037)
        INTEGER PGSMET_E_GROUP_NOT_FOUND
        PARAMETER (PGSMET_E_GROUP_NOT_FOUND = 10038)
        INTEGER PGSMET_E_INCOMP_GROUP
        PARAMETER (PGSMET_E_INCOMP_GROUP = 10039)
        INTEGER PGSMET_E_ODL_ERROR
        PARAMETER (PGSMET_E_ODL_ERROR = 10040)
        INTEGER PGSMET_W_ODL_WARNING
        PARAMETER (PGSMET_W_ODL_WARNING = 10041)
        INTEGER PGSMET_M_ODL_INFO
        PARAMETER (PGSMET_M_ODL_INFO = 10042)
        INTEGER PGSMET_E_MINMAX_ERR
        PARAMETER (PGSMET_E_MINMAX_ERR = 10043)
        INTEGER PGSMET_E_MCF_TYPE_CONFLICT
        PARAMETER (PGSMET_E_MCF_TYPE_CONFLICT = 10044)
        INTEGER PGSMET_E_MCF_NUMVAL_CONFLICT
        PARAMETER (PGSMET_E_MCF_NUMVAL_CONFLICT = 10045)
        INTEGER PGSMET_E_NESTED_OBJECTS
        PARAMETER (PGSMET_E_NESTED_OBJECTS = 10046)
        INTEGER PGSMET_E_ODL_MEM_ALLOC
        PARAMETER (PGSMET_E_ODL_MEM_ALLOC = 10047)
        INTEGER PGSMET_E_CLASS_PARAMETER
        PARAMETER (PGSMET_E_CLASS_PARAMETER = 10048)
        INTEGER PGSMET_E_METADATA_CHILD
        PARAMETER (PGSMET_E_METADATA_CHILD = 10049)
        INTEGER PGSMET_W_NOT_MULTIPLE
        PARAMETER (PGSMET_W_NOT_MULTIPLE = 10050)
        INTEGER PGSMET_E_NO_DEFINITION
        PARAMETER (PGSMET_E_NO_DEFINITION = 10051)
        INTEGER PGSMET_E_ILLEGAL_NUMVAL
        PARAMETER (PGSMET_E_ILLEGAL_NUMVAL = 10052)
        INTEGER PGSMET_E_ILLEGAL_TYPE
        PARAMETER (PGSMET_E_ILLEGAL_TYPE = 10053)
        INTEGER PGSMET_E_INV_DATATYPE
        PARAMETER (PGSMET_E_INV_DATATYPE = 10054)
        INTEGER PGSMET_E_PARENT_GROUP
        PARAMETER (PGSMET_E_PARENT_GROUP = 10055)
        INTEGER PGSMET_E_MANDATORY_FIELD
        PARAMETER (PGSMET_E_MANDATORY_FIELD = 10056)
        INTEGER PGSMET_E_MANDATORY_DEF
        PARAMETER (PGSMET_E_MANDATORY_DEF = 10057)
        INTEGER PGSMET_E_MANDATORY_VALUE
        PARAMETER (PGSMET_E_MANDATORY_VALUE = 10058)
        INTEGER PGSMET_E_LOC_FIELD
        PARAMETER (PGSMET_E_LOC_FIELD = 10059)
        INTEGER PGSMET_E_LOC_DEF
        PARAMETER (PGSMET_E_LOC_DEF = 10060)
        INTEGER PGSMET_E_LOC_VALUE
        PARAMETER (PGSMET_E_LOC_VALUE = 10061)
        INTEGER PGSMET_E_CONTAINER_LEVELS
        PARAMETER (PGSMET_E_CONTAINER_LEVELS = 10062)
        INTEGER PGSMET_E_DUPLICATE_ERR
        PARAMETER (PGSMET_E_DUPLICATE_ERR = 10063)
        INTEGER PGSMET_E_CLASS
        PARAMETER (PGSMET_E_CLASS = 10064)
        INTEGER PGSMET_E_CLASS_STATEMENTS
        PARAMETER (PGSMET_E_CLASS_STATEMENTS = 10065)
        INTEGER PGSMET_E_INV_NUMVAL
        PARAMETER (PGSMET_E_INV_NUMVAL = 10066)
        INTEGER PGSMET_E_CLASS_DEF
        PARAMETER (PGSMET_E_CLASS_DEF = 10067)
        INTEGER PGSMET_E_CLASS_TYPE
        PARAMETER (PGSMET_E_CLASS_TYPE = 10068)
        INTEGER PGSMET_E_MAND_NOT_SET
        PARAMETER (PGSMET_E_MAND_NOT_SET = 10069)
        INTEGER PGSMET_W_META_NOT_SET
        PARAMETER (PGSMET_W_META_NOT_SET = 10070)
        INTEGER PGSMET_W_METADATA_NOT_SET
        PARAMETER (PGSMET_W_METADATA_NOT_SET = 10071)
        INTEGER PGSMET_E_FGDC_ERR
        PARAMETER (PGSMET_E_FGDC_ERR = 10072)
        INTEGER PGSMET_E_OUTFILE_ERR
        PARAMETER (PGSMET_E_OUTFILE_ERR = 10073)
        INTEGER PGSMET_E_PCF_VALUE_ERR
        PARAMETER (PGSMET_E_PCF_VALUE_ERR = 10074)
        INTEGER PGSMET_E_GRP_ERR
        PARAMETER (PGSMET_E_GRP_ERR = 10075)
        INTEGER PGSMET_E_HDFNOTSET
        PARAMETER (PGSMET_E_HDFNOTSET = 10076)
        INTEGER PGSMET_E_HDFFILENAME_ERR
        PARAMETER (PGSMET_E_HDFFILENAME_ERR = 10077)
        INTEGER PGSMET_E_MET_ASCII_ERR
        PARAMETER (PGSMET_E_MET_ASCII_ERR = 10078)
        INTEGER PGSMET_E_ILLEGAL_HANDLE
        PARAMETER (PGSMET_E_ILLEGAL_HANDLE = 10079)
        INTEGER PGSMET_E_NUMOFMCF_ERR
        PARAMETER (PGSMET_E_NUMOFMCF_ERR = 10080)
        INTEGER PGSMET_E_GRP_NAME_ERR
        PARAMETER (PGSMET_E_GRP_NAME_ERR = 10081)
        INTEGER PGSMET_E_INVALID_LOCATION
        PARAMETER (PGSMET_E_INVALID_LOCATION = 10082)
        INTEGER PGSMET_E_NULL_PARAMETER
        PARAMETER (PGSMET_E_NULL_PARAMETER = 10083)
        INTEGER PGSMET_E_PARAMETER_NOT_SET
        PARAMETER (PGSMET_E_PARAMETER_NOT_SET = 10084)
        INTEGER PGSMET_E_SET_ATTRIBUTE_ERROR
        PARAMETER (PGSMET_E_SET_ATTRIBUTE_ERROR = 10085)
        INTEGER PGSMET_E_SEARCH_FAILED
        PARAMETER (PGSMET_E_SEARCH_FAILED = 10086)
        INTEGER PGSMET_E_GROUP_NOT_FOUND_IN_L7
        PARAMETER (PGSMET_E_GROUP_NOT_FOUND_IN_L7 = 10087)
        INTEGER PGSMET_W_OBJECT_NOT_SET
        PARAMETER (PGSMET_W_OBJECT_NOT_SET = 10088)
        INTEGER PGSMET_E_CONVERT_ERR
        PARAMETER (PGSMET_E_CONVERT_ERR = 10089)
        INTEGER PGSMET_E_TYPE_ERR
        PARAMETER (PGSMET_E_TYPE_ERR = 10090)
        INTEGER PGSMET_E_SET_ERR
        PARAMETER (PGSMET_E_SET_ERR = 10091)
        INTEGER PGSMET_E_ILLEGAL_LENGTH
        PARAMETER (PGSMET_E_ILLEGAL_LENGTH = 10092)
        INTEGER PGSMET_E_ARRAY_ELEMENT_SIZE
        PARAMETER (PGSMET_E_ARRAY_ELEMENT_SIZE = 10093)

        
        INTEGER PGS_E_UNIX
        PARAMETER (PGS_E_UNIX = 10094)
        INTEGER PGSSMF_M_UNIX
        PARAMETER (PGSSMF_M_UNIX = 10095)
        
        
        
        INTEGER PGSIO_E_FILEMAP
        PARAMETER (PGSIO_E_FILEMAP = 10096)
        INTEGER PGSIO_E_GEN_OPEN
        PARAMETER (PGSIO_E_GEN_OPEN = 10097)
        INTEGER PGSIO_E_GEN_OPENMODE
        PARAMETER (PGSIO_E_GEN_OPENMODE = 10098)
        INTEGER PGSIO_E_GEN_FILE_NOEXIST
        PARAMETER (PGSIO_E_GEN_FILE_NOEXIST = 10099)
        INTEGER PGSIO_E_GEN_NO_TEMP_NAME
        PARAMETER (PGSIO_E_GEN_NO_TEMP_NAME = 10100)
        INTEGER PGSIO_E_GEN_REFERENCE_FAILURE
        PARAMETER (PGSIO_E_GEN_REFERENCE_FAILURE = 10101)
        INTEGER PGSIO_E_GEN_CREATE_FAILURE
        PARAMETER (PGSIO_E_GEN_CREATE_FAILURE = 10102)
        INTEGER PGSIO_E_GEN_BAD_FILE_DURATION
        PARAMETER (PGSIO_E_GEN_BAD_FILE_DURATION = 10103)
        INTEGER PGSIO_W_GEN_ACCESS_MODIFIED
        PARAMETER (PGSIO_W_GEN_ACCESS_MODIFIED = 10104)
        INTEGER PGSIO_W_GEN_DURATION_NOMOD
        PARAMETER (PGSIO_W_GEN_DURATION_NOMOD = 10105)
        INTEGER PGSIO_W_GEN_NEW_FILE
        PARAMETER (PGSIO_W_GEN_NEW_FILE = 10106)
        INTEGER PGSIO_E_PARTIAL_NAME
        PARAMETER (PGSIO_E_PARTIAL_NAME = 10107)
        INTEGER PGSIO_E_GEN_NO_FREE_LUN
        PARAMETER (PGSIO_E_GEN_NO_FREE_LUN = 10108)
        INTEGER PGSIO_E_GEN_ILLEGAL_LUN
        PARAMETER (PGSIO_E_GEN_ILLEGAL_LUN = 10109)
        INTEGER PGSIO_W_GEN_UNUSED_LUN
        PARAMETER (PGSIO_W_GEN_UNUSED_LUN = 10110)
        INTEGER PGSIO_W_GEN_OLD_FILE
        PARAMETER (PGSIO_W_GEN_OLD_FILE = 10111)
        INTEGER PGSIO_E_GEN_OPEN_OLD
        PARAMETER (PGSIO_E_GEN_OPEN_OLD = 10112)
        INTEGER PGSIO_E_GEN_OPEN_NEW
        PARAMETER (PGSIO_E_GEN_OPEN_NEW = 10113)
        INTEGER PGSIO_E_GEN_OPEN_UNKNOWN
        PARAMETER (PGSIO_E_GEN_OPEN_UNKNOWN = 10114)
        INTEGER PGSIO_E_GEN_OPEN_RECL
        PARAMETER (PGSIO_E_GEN_OPEN_RECL = 10115)
        INTEGER PGSIO_E_GEN_FILE_NODEL
        PARAMETER (PGSIO_E_GEN_FILE_NODEL = 10116)
        INTEGER PGSIO_W_GEN_FILE_NOT_FOUND
        PARAMETER (PGSIO_W_GEN_FILE_NOT_FOUND = 10117)
        INTEGER PGSIO_E_GEN_CLOSE
        PARAMETER (PGSIO_E_GEN_CLOSE = 10118)
        INTEGER PGSIO_E_GEN_BAD_ENVIRONMENT
        PARAMETER (PGSIO_E_GEN_BAD_ENVIRONMENT = 10119)
        INTEGER PGSIO_E_L0_BAD_BUF_SIZ
        PARAMETER (PGSIO_E_L0_BAD_BUF_SIZ = 10120)
        INTEGER PGSIO_E_L0_BAD_SPACECRAFT_TAG
        PARAMETER (PGSIO_E_L0_BAD_SPACECRAFT_TAG = 10121)
        INTEGER PGSIO_E_L0_FSEEK
        PARAMETER (PGSIO_E_L0_FSEEK = 10122)
        INTEGER PGSIO_E_L0_MANAGE_TABLE
        PARAMETER (PGSIO_E_L0_MANAGE_TABLE = 10123)
        INTEGER PGSIO_E_L0_PHYSICAL_OPEN
        PARAMETER (PGSIO_E_L0_PHYSICAL_OPEN = 10124)
        INTEGER PGSIO_E_L0_UNEXPECTED_EOF
        PARAMETER (PGSIO_E_L0_UNEXPECTED_EOF = 10125)
        INTEGER PGSIO_E_L0_VIRTUAL_DS_NOT_OPEN
        PARAMETER (PGSIO_E_L0_VIRTUAL_DS_NOT_OPEN = 10126)
        INTEGER PGSIO_M_L0_HEADER_CHANGED
        PARAMETER (PGSIO_M_L0_HEADER_CHANGED = 10127)
        INTEGER PGSIO_W_L0_PKT_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_PKT_BUF_TRUNCATE = 10128)
        INTEGER PGSIO_W_L0_PHYSICAL_CLOSE
        PARAMETER (PGSIO_W_L0_PHYSICAL_CLOSE = 10129)
        INTEGER PGSIO_E_L0_INIT_FILE_TABLE
        PARAMETER (PGSIO_E_L0_INIT_FILE_TABLE = 10130)
        INTEGER PGSIO_E_L0_INVALID_FILE_LOGICAL
        PARAMETER (PGSIO_E_L0_INVALID_FILE_LOGICAL = 10131)
        INTEGER PGSIO_E_L0_MAP_VERSIONS
        PARAMETER (PGSIO_E_L0_MAP_VERSIONS = 10132)
        INTEGER PGSIO_E_L0_SEEK_1ST_PACKET
        PARAMETER (PGSIO_E_L0_SEEK_1ST_PACKET = 10133)
        INTEGER PGSIO_W_L0_TIME_NOT_FOUND
        PARAMETER (PGSIO_W_L0_TIME_NOT_FOUND = 10134)
        INTEGER PGSIO_E_L0_SEEK_PACKET
        PARAMETER (PGSIO_E_L0_SEEK_PACKET = 10135)
        INTEGER PGSIO_E_L0_PHYSICAL_NOT_OPEN
        PARAMETER (PGSIO_E_L0_PHYSICAL_NOT_OPEN = 10136)
        INTEGER PGSIO_E_L0_PKT_BUF_OVERFLOW
        PARAMETER (PGSIO_E_L0_PKT_BUF_OVERFLOW = 10137)
        INTEGER PGSIO_W_L0_END_OF_VIRTUAL_DS
        PARAMETER (PGSIO_W_L0_END_OF_VIRTUAL_DS = 10138)
        INTEGER PGSIO_E_L0_NEXT_PHYSICAL
        PARAMETER (PGSIO_E_L0_NEXT_PHYSICAL = 10139)
        INTEGER PGSIO_E_L0_ILLEGAL_COMMAND
        PARAMETER (PGSIO_E_L0_ILLEGAL_COMMAND = 10140)
        INTEGER PGSIO_E_L0_ILLEGAL_PACKET_NUM
        PARAMETER (PGSIO_E_L0_ILLEGAL_PACKET_NUM = 10141)
        INTEGER PGSIO_E_L0_INDEX_OUT_OF_RANGE
        PARAMETER (PGSIO_E_L0_INDEX_OUT_OF_RANGE = 10142)
        INTEGER PGSIO_E_L0_MAX_OPEN_EXCEEDED
        PARAMETER (PGSIO_E_L0_MAX_OPEN_EXCEEDED = 10143)
        INTEGER PGSIO_E_L0_MEM_ALLOC
        PARAMETER (PGSIO_E_L0_MEM_ALLOC = 10144)
        INTEGER PGSIO_E_L0_UNUSED_TABLE_ENTRY
        PARAMETER (PGSIO_E_L0_UNUSED_TABLE_ENTRY = 10145)
        INTEGER PGSIO_E_L0_VERSION_COUNT
        PARAMETER (PGSIO_E_L0_VERSION_COUNT = 10146)
        INTEGER PGSIO_E_L0_VERSION_INFO
        PARAMETER (PGSIO_E_L0_VERSION_INFO = 10147)
        INTEGER PGSIO_E_L0_PACKET_NOT_FOUND
        PARAMETER (PGSIO_E_L0_PACKET_NOT_FOUND = 10148)
        INTEGER PGSIO_E_L0_TIME_CONVERSION
        PARAMETER (PGSIO_E_L0_TIME_CONVERSION = 10149)
        INTEGER PGSIO_E_L0_BAD_FILEINFO
        PARAMETER (PGSIO_E_L0_BAD_FILEINFO = 10150)
        INTEGER PGSIO_E_L0_BAD_NUM_PKTS
        PARAMETER (PGSIO_E_L0_BAD_NUM_PKTS = 10151)
        INTEGER PGSIO_E_L0_BAD_APP_ID
        PARAMETER (PGSIO_E_L0_BAD_APP_ID = 10152)
        INTEGER PGSIO_E_L0_BAD_FIRST_PKTNUM
        PARAMETER (PGSIO_E_L0_BAD_FIRST_PKTNUM = 10153)
        INTEGER PGSIO_E_L0_BAD_DATA_LENGTH
        PARAMETER (PGSIO_E_L0_BAD_DATA_LENGTH = 10154)
        INTEGER PGSIO_E_L0_BAD_NUM_APP_IDS
        PARAMETER (PGSIO_E_L0_BAD_NUM_APP_IDS = 10155)
        INTEGER PGSIO_W_L0_HDR_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_HDR_BUF_TRUNCATE = 10156)
        INTEGER PGSIO_W_L0_FTR_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_FTR_BUF_TRUNCATE = 10157)
        INTEGER PGSIO_W_L0_ALL_BUF_TRUNCATE
        PARAMETER (PGSIO_W_L0_ALL_BUF_TRUNCATE = 10158)
        INTEGER PGSIO_W_L0_BUFTRUNC_END_DS
        PARAMETER (PGSIO_W_L0_BUFTRUNC_END_DS = 10159)
        INTEGER PGSIO_W_L0_BUFTRUNC_HDR_CHG
        PARAMETER (PGSIO_W_L0_BUFTRUNC_HDR_CHG = 10160)
        INTEGER PGSIO_E_L0_BUFTRUNC_NXTFILE
        PARAMETER (PGSIO_E_L0_BUFTRUNC_NXTFILE = 10161)
        INTEGER PGSIO_W_L0_HDR_TIME_ORDER
        PARAMETER (PGSIO_W_L0_HDR_TIME_ORDER = 10162)
        INTEGER PGSIO_E_L0_BAD_VAR_HDR_SIZE
        PARAMETER (PGSIO_E_L0_BAD_VAR_HDR_SIZE = 10163)
        INTEGER PGSIO_W_L0_BAD_PKT_DATA_SIZE
        PARAMETER (PGSIO_W_L0_BAD_PKT_DATA_SIZE = 10164)
        INTEGER PGSIO_W_L0_BAD_PACKET_COUNT
        PARAMETER (PGSIO_W_L0_BAD_PACKET_COUNT = 10165)
        INTEGER PGSIO_W_L0_BAD_FOOTER_SIZE
        PARAMETER (PGSIO_W_L0_BAD_FOOTER_SIZE = 10166)
        INTEGER PGSIO_W_L0_ZERO_PACKET_COUNT
        PARAMETER (PGSIO_W_L0_ZERO_PACKET_COUNT = 10167)
        INTEGER PGSIO_W_L0_CORRUPT_FILE_HDR
        PARAMETER (PGSIO_W_L0_CORRUPT_FILE_HDR = 10168)
 
        
        
        INTEGER PGSPC_E_FILE_OPEN_ERROR
        PARAMETER (PGSPC_E_FILE_OPEN_ERROR = 10169)
        INTEGER PGSPC_E_INVALID_MODE
        PARAMETER (PGSPC_E_INVALID_MODE = 10170)
        INTEGER PGSPC_W_NO_FILES_EXIST
        PARAMETER (PGSPC_W_NO_FILES_EXIST = 10171)
        INTEGER PGSPC_W_NO_CONFIG_VALUE
        PARAMETER (PGSPC_W_NO_CONFIG_VALUE = 10172)
        INTEGER PGSPC_E_FILE_READ_ERROR
        PARAMETER (PGSPC_E_FILE_READ_ERROR = 10173)
        INTEGER PGSPC_E_LINE_FORMAT_ERROR
        PARAMETER (PGSPC_E_LINE_FORMAT_ERROR = 10174)
        INTEGER PGSPC_E_ENVIRONMENT_ERROR
        PARAMETER (PGSPC_E_ENVIRONMENT_ERROR = 10175)
        INTEGER PGSPC_W_NO_DATA_PRESENT
        PARAMETER (PGSPC_W_NO_DATA_PRESENT = 10176)
        INTEGER PGSPC_E_DATA_ACCESS_ERROR
        PARAMETER (PGSPC_E_DATA_ACCESS_ERROR = 10177)
        INTEGER PGSPC_W_NO_REFERENCE_FOUND
        PARAMETER (PGSPC_W_NO_REFERENCE_FOUND = 10178)
        INTEGER PGSPC_W_NO_CONFIG_FOR_ID
        PARAMETER (PGSPC_W_NO_CONFIG_FOR_ID = 10179)
        INTEGER PGSPC_W_NO_FILES_FOR_ID
        PARAMETER (PGSPC_W_NO_FILES_FOR_ID = 10180)
        INTEGER PGSPC_W_NO_ATTR_FOR_ID
        PARAMETER (PGSPC_W_NO_ATTR_FOR_ID = 10181)
        INTEGER PGSPC_W_TRUNCATED
        PARAMETER (PGSPC_W_TRUNCATED = 10182)
        INTEGER PGSPC_W_ATTR_TRUNCATED
        PARAMETER (PGSPC_W_ATTR_TRUNCATED = 10183)
        INTEGER PGSPC_W_NO_ATTR_MATCH
        PARAMETER (PGSPC_W_NO_ATTR_MATCH = 10184)
        INTEGER PGSPC_W_INVALID_VERSION
        PARAMETER (PGSPC_W_INVALID_VERSION = 10185)
        INTEGER PGSPC_W_FILE_NOT_ON_DISK
        PARAMETER (PGSPC_W_FILE_NOT_ON_DISK = 10186)
        INTEGER PGSPC_W_NULL_DATA_SHM
        PARAMETER (PGSPC_W_NULL_DATA_SHM = 10187)
        INTEGER PGSPC_E_INV_DIVPOINTER_SHM
        PARAMETER (PGSPC_E_INV_DIVPOINTER_SHM = 10188)
        INTEGER PGSPC_E_EXCEEDED_SHM
        PARAMETER (PGSPC_E_EXCEEDED_SHM = 10189)
        INTEGER PGSPC_E_NO_DEFAULT_LOC
        PARAMETER (PGSPC_E_NO_DEFAULT_LOC = 10190)
        INTEGER PGSPC_E_ENV_NOT_PC
        PARAMETER (PGSPC_E_ENV_NOT_PC = 10191)
        INTEGER PGSPC_C_PGSINFO_PGE_START
        PARAMETER (PGSPC_C_PGSINFO_PGE_START = 10192)
        INTEGER PGSPC_C_PGSINFO_PGE_STOP
        PARAMETER (PGSPC_C_PGSINFO_PGE_STOP = 10193)
        INTEGER PGSPC_C_PGSINFO_TERM_START
        PARAMETER (PGSPC_C_PGSINFO_TERM_START = 10194)
        INTEGER PGSPC_M_TOOLKIT_INIT_PASS
        PARAMETER (PGSPC_M_TOOLKIT_INIT_PASS = 10195)
        INTEGER PGSPC_E_TOOLKIT_INIT_FAIL
        PARAMETER (PGSPC_E_TOOLKIT_INIT_FAIL = 10196)
        INTEGER PGSPC_M_TOOLKIT_TERM_BEGIN
        PARAMETER (PGSPC_M_TOOLKIT_TERM_BEGIN = 10197)
        INTEGER PGSPC_W_NO_UREF_DATA
        PARAMETER (PGSPC_W_NO_UREF_DATA = 10198)

        
        
        INTEGER PGSMEM_E_MAXSIZE
        PARAMETER (PGSMEM_E_MAXSIZE = 10199)
        INTEGER PGSMEM_E_NO_MEMORY
        PARAMETER (PGSMEM_E_NO_MEMORY = 10200)
        INTEGER PGSMEM_E_ADDR_NOTALLOC
        PARAMETER (PGSMEM_E_ADDR_NOTALLOC = 10201)
        INTEGER PGSMEM_W_MEMORY_USED
        PARAMETER (PGSMEM_W_MEMORY_USED = 10202)
        INTEGER PGSMEM_E_SHM
        PARAMETER (PGSMEM_E_SHM = 10203)
        INTEGER PGSMEM_E_SHM_NOTCREATE
        PARAMETER (PGSMEM_E_SHM_NOTCREATE = 10204)
        INTEGER PGSMEM_E_SHM_MULTICREATE
        PARAMETER (PGSMEM_E_SHM_MULTICREATE = 10205)
        INTEGER PGSMEM_E_SHM_MULTIATTACH
        PARAMETER (PGSMEM_E_SHM_MULTIATTACH = 10206)
        INTEGER PGSMEM_E_SHM_NOTATTACH
        PARAMETER (PGSMEM_E_SHM_NOTATTACH = 10207)
        INTEGER PGSMEM_E_SHM_MAXSIZE
        PARAMETER (PGSMEM_E_SHM_MAXSIZE = 10208)
        INTEGER PGSMEM_E_SHM_ENV
        PARAMETER (PGSMEM_E_SHM_ENV = 10209)
        INTEGER PGSMEM_E_SHM_INVALIDKEY
        PARAMETER (PGSMEM_E_SHM_INVALIDKEY = 10210)

        
        
        INTEGER PGSTD_M_ASCII_TIME_FMT_B
        PARAMETER (PGSTD_M_ASCII_TIME_FMT_B = 10211)
        INTEGER PGSTD_M_LEAP_SEC_IGNORED
        PARAMETER (PGSTD_M_LEAP_SEC_IGNORED = 10212)
        INTEGER PGSTD_M_TIME_TRUNCATED
        PARAMETER (PGSTD_M_TIME_TRUNCATED = 10213)
        INTEGER PGSTD_W_DATA_FILE_MISSING
        PARAMETER (PGSTD_W_DATA_FILE_MISSING = 10214)
        INTEGER PGSTD_W_JD_OUT_OF_RANGE
        PARAMETER (PGSTD_W_JD_OUT_OF_RANGE = 10215)
        INTEGER PGSTD_W_PRED_LEAPS
        PARAMETER (PGSTD_W_PRED_LEAPS = 10216)
        INTEGER PGSTD_W_BAD_SC_TIME
        PARAMETER (PGSTD_W_BAD_SC_TIME = 10217)
        INTEGER PGSTD_E_BAD_P_FIELD
        PARAMETER (PGSTD_E_BAD_P_FIELD = 10218)
        INTEGER PGSTD_E_DATE_OUT_OF_RANGE
        PARAMETER (PGSTD_E_DATE_OUT_OF_RANGE = 10219)
        INTEGER PGSTD_E_MICSEC_TOO_BIG
        PARAMETER (PGSTD_E_MICSEC_TOO_BIG = 10220)
        INTEGER PGSTD_E_MILSEC_TOO_BIG
        PARAMETER (PGSTD_E_MILSEC_TOO_BIG = 10221)
        INTEGER PGSTD_E_NO_LEAP_SECS
        PARAMETER (PGSTD_E_NO_LEAP_SECS = 10222)
        INTEGER PGSTD_E_SC_TAG_UNKNOWN
        PARAMETER (PGSTD_E_SC_TAG_UNKNOWN = 10223)
        INTEGER PGSTD_E_TIME_FMT_ERROR
        PARAMETER (PGSTD_E_TIME_FMT_ERROR = 10224)
        INTEGER PGSTD_E_TIME_VALUE_ERROR
        PARAMETER (PGSTD_E_TIME_VALUE_ERROR = 10225)
        INTEGER PGSTD_E_UNIX_ERROR
        PARAMETER (PGSTD_E_UNIX_ERROR = 10226)
        INTEGER PGSTD_E_NO_UT1_VALUE
        PARAMETER (PGSTD_E_NO_UT1_VALUE = 10227)
        INTEGER PGSTD_E_BAD_2ND_HDR_FLAG
        PARAMETER (PGSTD_E_BAD_2ND_HDR_FLAG = 10228)
        INTEGER PGSTD_E_BAD_INITIAL_TIME
        PARAMETER (PGSTD_E_BAD_INITIAL_TIME = 10229)
        INTEGER PGSTD_E_BAD_ARRAY_SIZE
        PARAMETER (PGSTD_E_BAD_ARRAY_SIZE = 10230)
        INTEGER PGSTD_E_SECONDS_TOO_BIG
        PARAMETER (PGSTD_E_SECONDS_TOO_BIG = 10231)
        INTEGER PGSTD_E_UTCF_UNINITIALIZED
        PARAMETER (PGSTD_E_UTCF_UNINITIALIZED = 10232)
        INTEGER PGSTD_E_TMDF_UNINITIALIZED
        PARAMETER (PGSTD_E_TMDF_UNINITIALIZED = 10233)

        
        INTEGER PGSCBP_E_NO_EPHEMERIS_DATA
        PARAMETER (PGSCBP_E_NO_EPHEMERIS_DATA = 10234)
        INTEGER PGSCBP_E_BAD_ARRAY_SIZE
        PARAMETER (PGSCBP_E_BAD_ARRAY_SIZE = 10235)
        INTEGER PGSCBP_E_BAD_TIME_FORMAT
        PARAMETER (PGSCBP_E_BAD_TIME_FORMAT = 10236)
        INTEGER PGSCBP_E_NO_MEMORY
        PARAMETER (PGSCBP_E_NO_MEMORY = 10237)
        INTEGER PGSCBP_E_BAD_CB_ID
        PARAMETER (PGSCBP_E_BAD_CB_ID = 10238)
        INTEGER PGSCBP_E_TIME_OUT_OF_RANGE
        PARAMETER (PGSCBP_E_TIME_OUT_OF_RANGE = 10239)
        INTEGER PGSCBP_W_EPHEMERIS_ERROR
        PARAMETER (PGSCBP_W_EPHEMERIS_ERROR = 10240)
        INTEGER PGSCBP_E_UNABLE_TO_READ_FILE
        PARAMETER (PGSCBP_E_UNABLE_TO_READ_FILE = 10241)
        INTEGER PGSCBP_E_UNABLE_TO_OPEN_FILE
        PARAMETER (PGSCBP_E_UNABLE_TO_OPEN_FILE = 10242)
        INTEGER PGSCBP_W_NOT_HEADER
        PARAMETER (PGSCBP_W_NOT_HEADER = 10243)
        INTEGER PGSCBP_E_INVALID_NCOEFF
        PARAMETER (PGSCBP_E_INVALID_NCOEFF = 10244)
        INTEGER PGSCBP_E_NO_OVERLAP
        PARAMETER (PGSCBP_E_NO_OVERLAP = 10245)
        INTEGER PGSCBP_W_NO_RECORD_WRITTEN
        PARAMETER (PGSCBP_W_NO_RECORD_WRITTEN = 10246)
        INTEGER PGSCBP_E_INVALID_CB_ID
        PARAMETER (PGSCBP_E_INVALID_CB_ID = 10247)
        INTEGER PGSCBP_E_NO_LIBRATIONS
        PARAMETER (PGSCBP_E_NO_LIBRATIONS = 10248)
        INTEGER PGSCBP_E_TARG_EQUAL_CENTER
        PARAMETER (PGSCBP_E_TARG_EQUAL_CENTER = 10249)
        INTEGER PGSCBP_E_INVALID_FILE_POS
        PARAMETER (PGSCBP_E_INVALID_FILE_POS = 10250)
        INTEGER PGSCBP_E_READ_RECORD_ERROR
        PARAMETER (PGSCBP_E_READ_RECORD_ERROR = 10251)
        INTEGER PGSCBP_E_INVALID_INT_FLAG
        PARAMETER (PGSCBP_E_INVALID_INT_FLAG = 10252)
        INTEGER PGSCBP_E_EPOCH_OUT_OF_SPAN
        PARAMETER (PGSCBP_E_EPOCH_OUT_OF_SPAN = 10253)
        INTEGER PGSCBP_E_NO_NUTATIONS
        PARAMETER (PGSCBP_E_NO_NUTATIONS = 10254)
        INTEGER PGSCBP_E_INVALID_BODY
        PARAMETER (PGSCBP_E_INVALID_BODY = 10255)
        INTEGER PGSCBP_E_BAD_INITIAL_TIME
        PARAMETER (PGSCBP_E_BAD_INITIAL_TIME = 10256)
        INTEGER PGSCBP_W_EARTH_CB_ID
        PARAMETER (PGSCBP_W_EARTH_CB_ID = 10257)
        INTEGER PGSCBP_W_BAD_CB_VECTOR
        PARAMETER (PGSCBP_W_BAD_CB_VECTOR = 10258)
        INTEGER PGSCBP_W_ERROR_IN_BODYINFOV
        PARAMETER (PGSCBP_W_ERROR_IN_BODYINFOV = 10259)

        
        
        INTEGER PGSCSC_W_JD_OUT_OF_RANGE
        PARAMETER (PGSCSC_W_JD_OUT_OF_RANGE = 10260)
        INTEGER PGSCSC_W_DATA_FILE_MISSING
        PARAMETER (PGSCSC_W_DATA_FILE_MISSING = 10261)
        INTEGER PGSCSC_E_BAD_DIRECTION_FLAG
        PARAMETER (PGSCSC_E_BAD_DIRECTION_FLAG = 10262)
        INTEGER PGSCSC_E_JD_WRONG_EPOCH
        PARAMETER (PGSCSC_E_JD_WRONG_EPOCH = 10263)
        INTEGER PGSCSC_E_ZERO_INPUT_VECTOR
        PARAMETER (PGSCSC_E_ZERO_INPUT_VECTOR = 10264)
        INTEGER PGSCSC_E_BAD_FLAT
        PARAMETER (PGSCSC_E_BAD_FLAT = 10265)
        INTEGER PGSCSC_E_NEG_OR_ZERO_RAD
        PARAMETER (PGSCSC_E_NEG_OR_ZERO_RAD = 10266)
        INTEGER PGSCSC_E_BAD_LAT
        PARAMETER (PGSCSC_E_BAD_LAT = 10267)
        INTEGER PGSCSC_E_BAD_LON
        PARAMETER (PGSCSC_E_BAD_LON = 10268)
        INTEGER PGSCSC_W_PROLATE_BODY
        PARAMETER (PGSCSC_W_PROLATE_BODY = 10269)
        INTEGER PGSCSC_W_SPHERE_BODY
        PARAMETER (PGSCSC_W_SPHERE_BODY = 10270)
        INTEGER PGSCSC_W_BELOW_SURFACE
        PARAMETER (PGSCSC_W_BELOW_SURFACE = 10271)
        INTEGER PGSCSC_E_BAD_ROT_AXIS_INDEX
        PARAMETER (PGSCSC_E_BAD_ROT_AXIS_INDEX = 10272)
        INTEGER PGSCSC_E_SC_TAG_UNKNOWN
        PARAMETER (PGSCSC_E_SC_TAG_UNKNOWN = 10273)
        INTEGER PGSCSC_E_TRANS_FLAG_ERR
        PARAMETER (PGSCSC_E_TRANS_FLAG_ERR = 10274)
        INTEGER PGSCSC_E_INVALID_VECTAG
        PARAMETER (PGSCSC_E_INVALID_VECTAG = 10275)
        INTEGER PGSCSC_W_BELOW_HORIZON
        PARAMETER (PGSCSC_W_BELOW_HORIZON = 10276)
        INTEGER PGSCSC_E_LOOK_PT_ALTIT_RANGE
        PARAMETER (PGSCSC_E_LOOK_PT_ALTIT_RANGE = 10277)
        INTEGER PGSCSC_W_UNDEFINED_AZIMUTH
        PARAMETER (PGSCSC_W_UNDEFINED_AZIMUTH = 10278)
        INTEGER PGSCSC_W_SUBTERRANEAN
        PARAMETER (PGSCSC_W_SUBTERRANEAN = 10279)
        INTEGER PGSCSC_W_TOO_MANY_ITERS
        PARAMETER (PGSCSC_W_TOO_MANY_ITERS = 10280)
        INTEGER PGSCSC_W_ZERO_JACOBIAN_DET
        PARAMETER (PGSCSC_W_ZERO_JACOBIAN_DET = 10281)
        INTEGER PGSCSC_W_DEFAULT_EARTH_MODEL
        PARAMETER (PGSCSC_W_DEFAULT_EARTH_MODEL = 10282)
        INTEGER PGSCSC_W_MISS_EARTH
        PARAMETER (PGSCSC_W_MISS_EARTH = 10283)
        INTEGER PGSCSC_W_INSTRUMENT_OFF_BOARD
        PARAMETER (PGSCSC_W_INSTRUMENT_OFF_BOARD = 10284)
        INTEGER PGSCSC_W_ZERO_PIXEL_VECTOR
        PARAMETER (PGSCSC_W_ZERO_PIXEL_VECTOR = 10285)
        INTEGER PGSCSC_W_BAD_ACCURACY_FLAG
        PARAMETER (PGSCSC_W_BAD_ACCURACY_FLAG = 10286)
        INTEGER PGSCSC_W_BAD_EPH_FOR_PIXEL
        PARAMETER (PGSCSC_W_BAD_EPH_FOR_PIXEL = 10287)
        INTEGER PGSCSC_E_INACCURATE_UTCPOLE
        PARAMETER (PGSCSC_E_INACCURATE_UTCPOLE = 10288)
        INTEGER PGSCSC_W_INTERIM_UT1
        PARAMETER (PGSCSC_W_INTERIM_UT1 = 10289)
        INTEGER PGSCSC_W_PREDICTED_UT1
        PARAMETER (PGSCSC_W_PREDICTED_UT1 = 10290)
        INTEGER PGSCSC_E_BAD_QUATERNION
        PARAMETER (PGSCSC_E_BAD_QUATERNION = 10291)
        INTEGER PGSCSC_W_ERRORS_IN_GHA
        PARAMETER (PGSCSC_W_ERRORS_IN_GHA = 10292)
        INTEGER PGSCSC_W_ERROR_IN_DAYNIGHT
        PARAMETER (PGSCSC_W_ERROR_IN_DAYNIGHT = 10293)
        INTEGER PGSCSC_W_BAD_TRANSFORM_VALUE
        PARAMETER (PGSCSC_W_BAD_TRANSFORM_VALUE = 10294)
        INTEGER PGSCSC_E_INVALID_LIMITTAG
        PARAMETER (PGSCSC_E_INVALID_LIMITTAG = 10295)
        INTEGER PGSCSC_E_BAD_ARRAY_SIZE
        PARAMETER (PGSCSC_E_BAD_ARRAY_SIZE = 10296)
        INTEGER PGSCSC_W_INVALID_ALTITUDE
        PARAMETER (PGSCSC_W_INVALID_ALTITUDE = 10297)
        INTEGER PGSCSC_W_LARGE_FLATTENING
        PARAMETER (PGSCSC_W_LARGE_FLATTENING = 10298)
        INTEGER PGSCSC_W_ERROR_IN_SUBSATPT
        PARAMETER (PGSCSC_W_ERROR_IN_SUBSATPT = 10299)
        INTEGER PGSCSC_W_NO_REFRACTION
        PARAMETER (PGSCSC_W_NO_REFRACTION = 10300)
        INTEGER PGSCSC_E_EULER_REP_INVALID
        PARAMETER (PGSCSC_E_EULER_REP_INVALID = 10301)
        INTEGER PGSCSC_E_EULER_INDEX_ERROR
        PARAMETER (PGSCSC_E_EULER_INDEX_ERROR = 10302)
        INTEGER PGSCSC_W_ACCURACY_SUSPECT
        PARAMETER (PGSCSC_W_ACCURACY_SUSPECT = 10303)
        INTEGER PGSCSC_E_QUAT_NOT_FOUND
        PARAMETER (PGSCSC_E_QUAT_NOT_FOUND = 10304)
        INTEGER PGSCSC_E_INVALID_FOV_DATA
        PARAMETER (PGSCSC_E_INVALID_FOV_DATA = 10305)
        INTEGER PGSCSC_E_FOV_TOO_LARGE
        PARAMETER (PGSCSC_E_FOV_TOO_LARGE = 10306)
        INTEGER PGSCSC_E_INVALID_EARTH_PT
        PARAMETER (PGSCSC_E_INVALID_EARTH_PT = 10307)
        INTEGER PGSCSC_M_EARTH_BLOCKS_CB
        PARAMETER (PGSCSC_M_EARTH_BLOCKS_CB = 10308)
        INTEGER PGSCSC_M_EARTH_BLOCKS_FOV
        PARAMETER (PGSCSC_M_EARTH_BLOCKS_FOV = 10309)
        INTEGER PGSCSC_M_CHECK_EARTH_BULGE
        PARAMETER (PGSCSC_M_CHECK_EARTH_BULGE = 10310)
        INTEGER PGSCSC_E_BAD_EARTH_MODEL
        PARAMETER (PGSCSC_E_BAD_EARTH_MODEL = 10311)
        INTEGER PGSCSC_W_ERROR_IN_EARTHPTFOV
        PARAMETER (PGSCSC_W_ERROR_IN_EARTHPTFOV = 10312)
        INTEGER PGSCSC_E_INVALID_ZENITH
        PARAMETER (PGSCSC_E_INVALID_ZENITH = 10313)
        INTEGER PGSCSC_E_BELOW_SURFACE
        PARAMETER (PGSCSC_E_BELOW_SURFACE = 10314)
        INTEGER PGSCSC_E_ABORT_UTCPOLE_UPDATE
        PARAMETER (PGSCSC_E_ABORT_UTCPOLE_UPDATE = 10315)
        INTEGER PGSCSC_W_ERROR_IN_GRAZINGRAY
        PARAMETER (PGSCSC_W_ERROR_IN_GRAZINGRAY = 10316)
        INTEGER PGSCSC_W_HIT_EARTH
        PARAMETER (PGSCSC_W_HIT_EARTH = 10317)
        INTEGER PGSCSC_W_LOOK_AWAY
        PARAMETER (PGSCSC_W_LOOK_AWAY = 10318)

        
        
        INTEGER PGSEPH_E_SIMULATOR_ERROR
        PARAMETER (PGSEPH_E_SIMULATOR_ERROR = 10319)
        INTEGER PGSEPH_W_BAD_EPHEM_VALUE
        PARAMETER (PGSEPH_W_BAD_EPHEM_VALUE = 10320)
        INTEGER PGSEPH_E_BAD_ARRAY_SIZE
        PARAMETER (PGSEPH_E_BAD_ARRAY_SIZE = 10321)
        INTEGER PGSEPH_E_NO_SC_EPHEM_FILE
        PARAMETER (PGSEPH_E_NO_SC_EPHEM_FILE = 10322)
        INTEGER PGSEPH_E_BAD_EPHEM_FILE_HDR
        PARAMETER (PGSEPH_E_BAD_EPHEM_FILE_HDR = 10323)
        INTEGER PGSEPH_E_BAD_TIME_ORDER
        PARAMETER (PGSEPH_E_BAD_TIME_ORDER = 10324)
        INTEGER PGSEPH_E_NO_DATA_REQUESTED
        PARAMETER (PGSEPH_E_NO_DATA_REQUESTED = 10325)
        INTEGER PGSEPH_M_SHORT_ARRAY
        PARAMETER (PGSEPH_M_SHORT_ARRAY = 10326)
        
        
        
        
        INTEGER PGSCUC_E_CANT_GET_FILE_ID
        PARAMETER (PGSCUC_E_CANT_GET_FILE_ID = 10327)
        INTEGER PGSCUC_E_CANT_OPEN_INPUT_FILE
        PARAMETER (PGSCUC_E_CANT_OPEN_INPUT_FILE = 10328)
        INTEGER PGSCUC_E_AGG_CANT_BE_INSERTED
        PARAMETER (PGSCUC_E_AGG_CANT_BE_INSERTED = 10329)
        INTEGER PGSCUC_E_READLABEL_PARSE_ERROR
        PARAMETER (PGSCUC_E_READLABEL_PARSE_ERROR = 10330)
        INTEGER PGSCUC_E_PARAMETER_INVALID
        PARAMETER (PGSCUC_E_PARAMETER_INVALID = 10331)
        INTEGER PGSCUC_E_FIRST_NODE_NOT_FOUND
        PARAMETER (PGSCUC_E_FIRST_NODE_NOT_FOUND = 10332)
        INTEGER PGSCUC_E__ERROR
        PARAMETER (PGSCUC_E__ERROR = 10333)
        INTEGER PGSCUC_E_COULDNT_INIT_UDUNITS3
        PARAMETER (PGSCUC_E_COULDNT_INIT_UDUNITS3 = 10334)
        INTEGER PGSCUC_E_DONT_KNOW_INP_UNIT
        PARAMETER (PGSCUC_E_DONT_KNOW_INP_UNIT = 10335)
        INTEGER PGSCUC_E_DONT_KNOW_OUTP_UNIT
        PARAMETER (PGSCUC_E_DONT_KNOW_OUTP_UNIT = 10336)
        INTEGER PGSCUC_E_UNITS_ARE_INCOMPATIBLE
        PARAMETER (PGSCUC_E_UNITS_ARE_INCOMPATIBLE = 10337)
        INTEGER PGSCUC_E_A_UNIT_IS_CORRUPTED
        PARAMETER (PGSCUC_E_A_UNIT_IS_CORRUPTED = 10338)
        INTEGER PGSTD_M_HEADER_UPDATED
        PARAMETER (PGSTD_M_HEADER_UPDATED = 10339)
        INTEGER PGS_E_TOOLKIT
        PARAMETER (PGS_E_TOOLKIT = 10340)
        INTEGER PGSMET_E_GETSET_ATTRIBUTE_ERROR
        PARAMETER (PGSMET_E_GETSET_ATTRIBUTE_ERROR = 10341)
        INTEGER PGSMET_M_METADATA_NOT_SET_TK
        PARAMETER (PGSMET_M_METADATA_NOT_SET_TK = 10342)
        INTEGER PGSMET_M_METADATA_NOT_SET_PGE
        PARAMETER (PGSMET_M_METADATA_NOT_SET_PGE = 10343)
